name: base
channels: 
    - conda-forge
    - geo-down-under    
dependencies:
    - python=3.8
    - ipython # helpful for debugging in terminal
    - numpy
    - nodejs
    - pip 
    - libiconv
    - cartopy
    - pillow
    - gdal
    - libgdal
    - obspy
    - pandas
    - xarray
    - jupytext
    - h5netcdf
    - netcdf4
    - compilers
    - pip:
        - stripy
        - litho1pt0
        - cloudstor
    #   - lavavu<1.7


      
      


