name: base
channels: 
    - conda-forge
    - geo-down-under    
dependencies:
    - pip 
    - cartopy
    - pillow
    - gdal
    - libgdal
    - matplotlib
    - pandas
    - xarray
    - h5netcdf
    - netcdf4
    - jupytext
    - compilers
    - obspy
    - pip:
        - stripy
        - litho1pt0
        - cloudstor


      
      


