name: jupyter
channels: 
    - conda-forge
    - geo-down-under    
dependencies:
    - numpy
    - nodejs
    - pip 
    - libiconv
    - cloudstor
    - stripy
    - litho1pt0
    # - proj=7.*.        # errors with cartopy when 6.2.* is used
    - cartopy=0.19.*
    - gdal
    - libgdal
    - obspy
    - pandas
    - xarray
    - jupytext
    - h5netcdf
    - netcdf4
    # - pip:
    #   - lavavu<1.7


      
      


