name: base
channels: 
    - conda-forge
    - geo-down-under    
dependencies:
    - cartopy
    - pillow
    - gdal
    - libgdal
    - matplotlib
    - pandas
    - xarray
    - h5netcdf
    - netcdf4
    - jupytext
    - compilers
    - obspy
    # - libiconv
    - pip:
        - stripy
        - litho1pt0
        - cloudstor
    #   - lavavu<1.7


      
      


