# Exercise: Comparative Planetology

This practical session will give you a good sense of how planetary
scientists approach their work. We are going to create a short "presentation"
(you will just need to provide some powerpoint / pdf slides, not present to the class).

The slides that you will produce are outlined below.
You will need to look up the information and cite your sources.
Make sure you explain terms or have an explanation ready in the speaker notes.

Note: Advanced-level students, please write two slides for each of 1 through 6 below:
a general, explanatory slide and another with detailed comparison of one additional
example (e.g. for slide 1, include another planetary surface in addition to Mars;
in slide 2, show examples of both rock volcanoes and cryvolcanos)

Instructions for each slide are *the italic text* under the title.

## Title slide: Earth — is it just like any other planet ?

*Make sure you include your name and an
"interesting" image of the Earth, an equivalent image of
one of the other planets, and include a caption*

## Slide 1: Topography

*The Earth's topography is "bimodal" and so is the topography of Mars.
Explain what that means (in a technical sense) and show what this looks
like each case.*

## Slide 2: Volcanoes

*There are volcanoes in many places in the solar system.
Not all of them erupt molten rock - can you find an example of one of those ?
Find some images of volcanoes from Earth and from one or two other places
in the solar system for your slide. Which is the largest volcano we know about,
is it on Earth ?*

## Slide 3: Surface Erosion/ Weather / Rivers etc

*The Earth's surface is heavily influenced by surface erosion and
sedimentation due to rain, landslides and so on.
Can you find an image that highlights this on Earth and are there similar processes somewhere else in the solar system. Similar here could just be "looks the same" (hint - Mars and Titan!)*

## Slide 4: Surface Age

*The Earth has a very distinctive pattern of surface age
(continents different from oceans, oceans have an age pattern).  Make a slide that contrasts this with planet that also has a bimodal age distribution (e.g. Mars, the Moon) and point out the differences / how we know the information we do.*

*You should be sure to define what a **craton** is and why this is interesting in telling
the story of surface age for the Earth*

## Slide 5: Faults

*Find a few images of faults from the Earth and at
least one from another world. Faults are very important in geophysics / geology
and are the places most earthquakes are generated.*

*Include a definition of a **fault** for your slide.*

## Slide 6: Habitability / Life

*What do we look for in suggesting a planet could be habitable ? In the solar
system, where are there habitable zones now and where might there have been
habitable zones in the past ?  Why might that change over the age of the solar
system ?*

## Conclusion Slide:

*Geology / geophysics has many common processes across different planets.
How special is the Earth ? Give your opinion on how likely we are to find
Earth-like exoplanets!*

## References Slide:

*Add a final slide with full citations of your references from the slides*
