## Course Content

The broad themes of the course and these materials are split into three sections

- Introduction to Geophysics
- Module i - Global Geodynamics (this section)
- Module ii - Seismology

### Introduction

Introduces the concepts of global-scale tectonics, plate motions, the nature of plate boundaries and the underlying mantle circulation that drives geological deformation.

 - [1. What the Solar System Tells us About the Earth](LectureDescriptions/Lecture_Planets)
 - [2. The Ocean Floors Revealed](LectureDescriptions/Lecture_HistoryOfData)

### Module i - Global Geodynamics

 - [3. Continuum Mechanics & Convection](LectureDescriptions/Lecture_Continuum_Mechanics_bg)
 - [4. Convection and Heat Flow](LectureDescriptions/Lecture_Convection_HeatFlow)
 - [5. Lithospheric Dynamics](LectureDescriptions/Lecture_Lithosphere)

This "lecture" is an introduction to the plate kinematics exercise

 - [A. Plate Boundary Kinematics & Reconstruction](LectureDescriptions/Lecture_PlateKinematics)

### Module ii - Seismology
